config/routes.rb
Rails.application.routes.draw do
  get     'cart'            => 'cart#index',        as: :cart
  post    'cart/add/:id'    => 'cart#add_item',     as: :cart_add_item
  post    'cart/checkout'   => 'cart#checkout',     as: :checkout
  delete  'cart/empty'      => 'cart#empty',        as: :cart_empty
  delete  'cart/remove/:id' => 'cart#remove_item',  as: :cart_remove_item

  post  'payments/notify'
  get   'payments/success'
  get   'payments/check'

  get   'account_settings'        => 'account_settings#index'
  post  'account_settings/update' => 'account_settings#update'

  post 'currencies/set_currency/:currency' => 'currencies#set_currency', as: :set_currency

  resources :orders, only: [:index, :show]

  root 'items#index'
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
    respond_to do |format|
      format.html { render }
      format.js { render layout: false }
    end
  end

  def add_item
    @cart.add_item(params[:id])

    render json: true
  end

  def remove_item
    @cart.remove_item(params[:id])

    redirect_to cart_path
  end

  def empty
    @cart.empty

    render json: { }
  end

  def checkout
    order = Order.create(
      total:          @cart.total,
      shipping_price: @cart.shipping_price,
      status:         'pending',
      currency:       current_currency,
      currency_rate:  current_currency_rate,
      token:          SecureRandom.urlsafe_base64
    )

    @cart.items.each do |cart_item|
      order.order_items.create(item_id: cart_item.item.id, quantity: cart_item.quantity, price: (cart_item.item.price * order.currency_rate).round(CoingateService::CRYPTO_CURRENCIES.include?(order.currency) ? 6 : 2))
    end

    session[:current_order] = order.id

    @cart.empty

    response = coingate_client.create_order(
      order_id:             "ORDER-#{(Time.now.to_f * 1e6).to_i}-#{order.id}",
      price_amount:         order.total,
      price_currency:       order.currency,
      receive_currency:     current_receive_currency,
      title:                "Order ##{order.id}",
      description:          order.description,
      callback_url:         payments_notify_url(token: order.token),
      success_url:          payments_success_url,
      cancel_url:           root_url,
      success_auto_return:  1
    )

    if response.success?
      order.update_attributes(coingate_id: response.response[:id], coingate_status: response.response[:status])

      redirect_to response.response[:payment_url]
    else
      order.update_attribute(:status, 'failure')
      order.order_failures.create(http_status: response.http_code, reason: response.reason, message: response.response)

      redirect_to order_path(order.id), flash: { error: 'Ooops! Something wrong. Please try again or contact with support' }
    end
  end
end

app/views/cart/index.js.erb
$('#cart-panel').html('<%= escape_javascript(render("_partials/cart")) %>');

app/views/cart/index.slim
- title 'Shopping Cart'

.row
  .col-md-12
    - if @cart.items.any?
      table.table.table-hover
        thead
          tr
            th Product
            th.text-center Quantity
            th.text-center Price
            th.text-center Total
            th
        tbody
          - @cart.items.each do |cart_item|
            tr
              td.col-md-6
                .media
                  .media-left
                    = image_tag "items/#{cart_item.item.id}_thumb.jpg", class: 'thumbnail', alt: cart_item.item.title
                  .media-body
                    h4.media-heading = cart_item.item.title
                    span> Status:
                    span.text-success
                      b In Stock
              td.text-center
                = cart_item.quantity
              td.text-center
                = formatted_price((cart_item.item.price * current_currency_rate).round(currency_round_value))
              td.text-center
                = formatted_price(cart_item.total_price)
              td.text-right
                = link_to fa_icon('trash') + ' Remove', cart_remove_item_path(cart_item.item.id), class: 'btn btn-danger btn-sm', method: :delete
      
      .clearfix
        .pull-right
          dl.dl-horizontal.cart-summary
            dt Item(s) Subtotal
            dd = formatted_price(@cart.subtotal)
            dt Shipping &amp; Handling
            dd = formatted_price(@cart.shipping_price)

      hr

      .clearfix
        .pull-right
          dl.dl-horizontal.cart-summary
            dt Total
            dd = formatted_price(@cart.total)



      .clearfix
        .pull-right
          =' link_to fa_icon('shopping-cart') + ' Continue Shopping', root_path, class: 'btn btn-default'
          =' link_to 'Checkout', checkout_path, class: 'btn btn-success', method: :post, data: { disable_with: 'Please Wait...' }
    - else
      p Your cart is empty