config/routes.rb
Rails.application.routes.draw do
  get     'cart'            => 'cart#index',        as: :cart
  post    'cart/add/:id'    => 'cart#add_item',     as: :cart_add_item
  post    'cart/checkout'   => 'cart#checkout',     as: :checkout
  delete  'cart/empty'      => 'cart#empty',        as: :cart_empty
  delete  'cart/remove/:id' => 'cart#remove_item',  as: :cart_remove_item

  post  'payments/notify'
  get   'payments/success'
  get   'payments/check'

  get   'account_settings'        => 'account_settings#index'
  post  'account_settings/update' => 'account_settings#update'

  post 'currencies/set_currency/:currency' => 'currencies#set_currency', as: :set_currency

  resources :orders, only: [:index, :show]

  root 'items#index'
end

app/controllers/account_settings_controller.rb
class AccountSettingsController < ApplicationController
  def index
    
  end

  def update
    session[:receive_currency] = params[:receive_currency]

    redirect_to account_settings_path
  end
end

app/views/account_settings/index.slim
h1 My Settings

= form_tag account_settings_update_path, class: 'form-horizontal' do
  .form-group
    label.control-label.col-sm-2 Receive Currency
    .col-sm-10
      ul.list-unstyled
        - currencies.each do |currency_iso, currency_data|
          - currency_iso = currency_iso.to_s.upcase
          li
            .radio
              label
                =' radio_button_tag :receive_currency, currency_iso, currency_iso == current_receive_currency
                =' currency_icon(currency_iso.downcase)
                = currency_data[:title]

  = submit_tag 'Update', class: 'btn btn-primary', data: { disable_with: 'Please Wait...' }