config/routes.rb
Rails.application.routes.draw do
  get     'cart'            => 'cart#index',        as: :cart
  post    'cart/add/:id'    => 'cart#add_item',     as: :cart_add_item
  post    'cart/checkout'   => 'cart#checkout',     as: :checkout
  delete  'cart/empty'      => 'cart#empty',        as: :cart_empty
  delete  'cart/remove/:id' => 'cart#remove_item',  as: :cart_remove_item

  post  'payments/notify'
  get   'payments/success'
  get   'payments/check'

  get   'account_settings'        => 'account_settings#index'
  post  'account_settings/update' => 'account_settings#update'

  post 'currencies/set_currency/:currency' => 'currencies#set_currency', as: :set_currency

  resources :orders, only: [:index, :show]

  root 'items#index'
end

app/views/_partials/_cart.slim
- if @cart.items.any?
  ul.list-unstyled
    - @cart.items.each do |cart_item|
      li
        .clearfix
          ' #{cart_item.quantity} x
          =' cart_item.item.title.truncate(17)
          .pull-right
            span.text-primary
              = formatted_price(cart_item.total_price)
  hr
  
  .clearfix
    .pull-right
      h4 Total: #{formatted_price(@cart.subtotal)}
  
  .clearfix
    .pull-left
      = link_to fa_icon('trash') + ' Empty Cart', cart_empty_path, id: 'cart-empty', class: 'btn btn-sm btn-default', method: :delete, remote: true
    .pull-right
      = link_to 'Checkout', cart_path, class: 'btn btn-sm btn-success'
- else
  p Your shopping cart is empty.

app/views/_partials/_notifications.slim
- if flash[:error]
  .alert.alert-danger = flash[:error]

- if flash[:success]
  .alert.alert-success = flash[:success]