config/routes.rb
Rails.application.routes.draw do
  get     'cart'            => 'cart#index',        as: :cart
  post    'cart/add/:id'    => 'cart#add_item',     as: :cart_add_item
  post    'cart/checkout'   => 'cart#checkout',     as: :checkout
  delete  'cart/empty'      => 'cart#empty',        as: :cart_empty
  delete  'cart/remove/:id' => 'cart#remove_item',  as: :cart_remove_item

  post  'payments/notify'
  get   'payments/success'
  get   'payments/check'

  get   'account_settings'        => 'account_settings#index'
  post  'account_settings/update' => 'account_settings#update'

  post 'currencies/set_currency/:currency' => 'currencies#set_currency', as: :set_currency

  resources :orders, only: [:index, :show]

  root 'items#index'
end

app/views/layouts/application.slim
doctype html
html
  head
    meta charset="utf-8"
    title #{ yield(:title) } CoinGate Shop Demo

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

= content_tag :body, data: { controller: controller.controller_path, action: controller.action_name }
  nav.navbar.navbar-default.navbar-static-top
    .container-fluid
      = link_to 'CoinGate Shop Demo', root_path, class: 'navbar-brand'
      
      ul.nav.navbar-nav
        li = link_to fa_icon('question') + ' Read the Guide', 'https://support.coingate.com/en/74/guide-to-using-the-coingate-example-demo-shop', target: :_blank
        li = link_to fa_icon('code') + ' Source Code', 'https://github.com/coingate/rails-shop-example', target: :_blank
        li = link_to fa_icon('cogs') + ' Integration', 'https://coingate.com/accept-bitcoin', target: :_blank
        li = link_to fa_icon('home') + ' Homepage', 'https://coingate.com', target: :_blank

      ul.nav.navbar-nav.navbar-right
        li
          p.navbar-text
            small = currency_rate_info
        li.dropdown
          a.dropdown-toggle href="javascript:;" data-toggle="dropdown"
            =' currency_icon(current_currency.downcase)
            =' current_currency
            b.caret
          ul.dropdown-menu role="menu"
            - currencies.each do |iso, data|
              li = link_to currency_icon(iso) + ' ' + data[:title], set_currency_path(iso.upcase), method: :post
        li.dropdown
          a.dropdown-toggle href="javascript:;" data-toggle="dropdown"
            =' fa_icon('user')
            | My Account
            b.caret
          ul.dropdown-menu role="menu"
            li = link_to fa_icon('cogs') + ' My Settings', account_settings_path
            li = link_to fa_icon('shopping-cart') + ' Cart', cart_path
            li = link_to fa_icon('briefcase') + ' Orders', orders_path
            li = link_to fa_icon('user-plus') + ' Sign Up', 'https://coingate.com/sign_up'


  .container
    = render_breadcrumbs

    = yield

  footer